version: '3'

services:
  nginx:
    build: 
      context: ./nginx
    container_name: nginx
    networks:
      - node-network
    ports:
      - "8080:80"
    depends_on:
      - app

  app:
    build: 
      context: ./node
    container_name: nodejs
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s node index
    networks:
      - node-network
    volumes:
      - ./node:/usr/src/app
    expose:
      - "3000"
    depends_on:
      - db

  db:
    image: mysql
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: nodedb
    expose:
      - "3306"
    networks:
      - node-network

networks:
  node-network:
    driver: bridge

volumes:
  mysql:
  